<a href="https://colab.research.google.com/github/AIPythonILP-teamB/AIPythonILP-teamB-Python/blob/main/quick_look_profit_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
# Matplotlibで日本語を正しく表示するためのライブラリをインストール
!pip install japanize-matplotlib

Requirement already satisfied: japanize-matplotlib in /usr/local/lib/python3.11/dist-packages (1.1.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from japanize-matplotlib) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->japanize-matplotlib) (1.17.0)

In [63]:
# 数値計算を行うライブラリ numpy をインポート
import numpy as np
# 表データを扱うライブラリ pandas をインポート
import pandas as pd
# 図や表を描画するためのライブラリをインポート
import matplotlib.pyplot as plt
import japanize_matplotlib
import seaborn as sns

In [64]:
#データセットを取得
df = pd.read_csv("profit.csv")
df = df[df['日付'] != '日付']
df = df.drop(['予約件数', '予約人数'], axis=1)

In [65]:
df.head()

,日付,曜日,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
0,2024/4/1,月,16,25,25300,6,6000,5,4000,5,4500,4,3600,6,7200,0,0
1,2024/4/2,火,19,25,24600,6,6000,4,3200,5,4500,3,2700,6,7200,1,1000
2,2024/4/3,水,11,19,18500,5,5000,4,3200,3,2700,2,1800,4,4800,1,1000
3,2024/4/4,木,6,10,9500,2,2000,2,1600,2,1800,1,900,1,1200,2,2000
4,2024/4/5,金,10,18,17100,3,3000,5,4000,3,2700,2,1800,3,3600,2,2000

In [66]:
# 変数の確認
df.columns.values

array(['日付', '曜日', '来客数', '総杯数', '売上合計(円)', 'ペールエール(本)', 'ペールエール(円)',
       'ラガー(本)', 'ラガー(円)', 'IPA(本)', 'IPA(円)', 'ホワイトビール(本)', 'ホワイトビール(円)',
       '黒ビール(本)', '黒ビール(円)', 'フルーツビール(本)', 'フルーツビール(円)'], dtype=object)

In [67]:
# データの行数と列数を確認
df.shape

(314, 17)

In [68]:
df.tail()  # 默认显示最后5行

,日付,曜日,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
309,2025/3/27,木,10,14,13400,2,2000,3,2400,2,1800,2,1800,2,2400,3,3000
310,2025/3/28,金,14,28,26900,6,6000,7,5600,3,2700,4,3600,5,6000,3,3000
311,2025/3/29,土,6,8,7600,2,2000,2,1600,1,900,1,900,1,1200,1,1000
312,2025/3/31,月,9,15,14800,4,4000,2,1600,2,1800,2,1800,3,3600,2,2000
313,2025/4/1,火,5,6,5800,1,1000,1,800,1,900,1,900,1,1200,1,1000

In [69]:
# データ型の確認 float
df.dtypes

日付            object
曜日            object
来客数            int64
総杯数            int64
売上合計(円)        int64
ペールエール(本)      int64
ペールエール(円)      int64
ラガー(本)         int64
ラガー(円)         int64
IPA(本)         int64
IPA(円)         int64
ホワイトビール(本)     int64
ホワイトビール(円)     int64
黒ビール(本)        int64
黒ビール(円)        int64
フルーツビール(本)     int64
フルーツビール(円)     int64
dtype: object

In [70]:
# 各種統計量の確認
df.describe()

,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
count,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000
mean,13.124204,22.165605,21135.987261,5.015924,5015.923567,4.987261,3989.808917,3.570064,3213.057325,3.121019,2808.917197,3.025478,3630.573248,2.477707,2477.707006
std,5.437462,10.932174,10295.993722,2.579670,2579.670077,2.865432,2292.345499,1.882286,1694.056953,1.959169,1763.251998,1.710516,2052.619690,1.927060,1927.059662
min,2.000000,4.000000,4600.000000,1.000000,1000.000000,1.000000,800.000000,1.000000,900.000000,1.000000,900.000000,0.000000,0.000000,0.000000,0.000000
25%,9.000000,14.000000,13500.000000,3.000000,3000.000000,3.000000,2400.000000,2.000000,1800.000000,2.000000,1800.000000,2.000000,2400.000000,1.000000,1000.000000
50%,13.000000,22.000000,20450.000000,5.000000,5000.000000,5.000000,4000.000000,3.000000,2700.000000,3.000000,2700.000000,3.000000,3600.000000,2.000000,2000.000000
75%,17.000000,28.000000,26800.000000,6.000000,6000.000000,6.000000,4800.000000,5.000000,4500.000000,4.000000,3600.000000,4.000000,4800.000000,4.000000,4000.000000
max,30.000000,66.000000,62900.000000,20.000000,20000.000000,17.000000,13600.000000,11.000000,9900.000000,14.000000,12600.000000,11.000000,13200.000000,10.000000,10000.000000

In [71]:
df.notnull().sum()

日付            314
曜日            314
来客数           314
総杯数           314
売上合計(円)       314
ペールエール(本)     314
ペールエール(円)     314
ラガー(本)        314
ラガー(円)        314
IPA(本)        314
IPA(円)        314
ホワイトビール(本)    314
ホワイトビール(円)    314
黒ビール(本)       314
黒ビール(円)       314
フルーツビール(本)    314
フルーツビール(円)    314
dtype: int64

In [73]:
df.to_csv('sales_data_cleaned.csv', index=False)