<a href="https://colab.research.google.com/github/AIPythonILP-teamB/AIPythonILP-teamB-Python/blob/main/quick_look_profit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Matplotlibで日本語を正しく表示するためのライブラリをインストール
!pip install japanize-matplotlib

Collecting japanize-matplotlib
  Downloading japanize-matplotlib-1.1.3.tar.gz (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 31.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from japanize-matplotlib) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->japanize-matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->japanize-matplotlib) (1.17.0)
Building wheels for collected packages: japanize-matplotlib
  Building wheel for japanize-matplotlib (setup.py) ... done
  Created wheel for japanize-matplotlib: filename=japanize_matplotlib-1.1.3-py3-none-any.whl size=4120257 sha256=9ce6f1eaf0cdb53eac23ade57f8f8442b6a5593eac60bccfb8b6517345aa96d8
  Stored in directory: /root/.cache/pip/wheels/da/a1/71/b8faeb93276fed10edffcca20746f1ef6f8d9e071eee8425fc
Successfully built japanize-matplotlib
Installing collected packages: japanize-matplotlib
Successfully installed japanize-matplotlib-1.1.3

In [ ]:
# 数値計算を行うライブラリ numpy をインポート
import numpy as np
# 表データを扱うライブラリ pandas をインポート
import pandas as pd
# 図や表を描画するためのライブラリをインポート
import matplotlib.pyplot as plt
import japanize_matplotlib
import seaborn as sns

In [ ]:
#データセットを取得
df = pd.read_csv("profit.csv")
df = df[df['日付'] != '日付']

In [ ]:
df.head()

,日付,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
0,2024/04/01,NaN,NaN,21,33,"31,800",10,"10,000",10,"8,000",5,"4,500",5,"4,500",4,"4,800",NaN,NaN
1,2024/04/02,NaN,NaN,13,25,"23,300",8,"8,000",7,"5,600",3,"2,700",4,"3,600",2,"2,400",1,"1,000"
2,2024/04/03,NaN,NaN,20,36,"33,600",7,"7,000",8,"6,400",6,"5,400",6,"5,400",2,"2,400",7,"7,000"
3,2024/04/04,NaN,NaN,17,27,"24,600",6,"6,000",9,"7,200",4,"3,600",4,"3,600",1,"1,200",3,"3,000"
4,2024/04/05,2,5,29,61,"56,500",15,"15,000",18,"14,400",9,"8,100",8,"7,200",4,"4,800",7,"7,000"

In [ ]:
# 変数の確認
df.columns.values

array(['日付', '予約件数', '予約人数', '来客数', '総杯数', '売上合計(円)', 'ペールエール(本)',
       'ペールエール(円)', 'ラガー(本)', 'ラガー(円)', 'IPA(本)', 'IPA(円)', 'ホワイトビール(本)',
       'ホワイトビール(円)', '黒ビール(本)', '黒ビール(円)', 'フルーツビール(本)', 'フルーツビール(円)'],
      dtype=object)

In [ ]:
# データの行数と列数を確認
df.shape

(315, 18)

In [ ]:
# データ型の確認 float
df.dtypes

日付            object
予約件数          object
予約人数          object
来客数           object
総杯数           object
売上合計(円)       object
ペールエール(本)     object
ペールエール(円)     object
ラガー(本)        object
ラガー(円)        object
IPA(本)        object
IPA(円)        object
ホワイトビール(本)    object
ホワイトビール(円)    object
黒ビール(本)       object
黒ビール(円)       object
フルーツビール(本)    object
フルーツビール(円)    object
dtype: object

In [ ]:
obj_cols = df.select_dtypes(include='object').columns

In [ ]:
obj_cols = obj_cols.drop("日付")

In [ ]:
df[obj_cols] = df[obj_cols].apply(lambda col: col.str.replace(',', '') if col.dtypes == 'object' else col)

In [ ]:
df[obj_cols].head()

,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
0,NaN,NaN,21,33,31800,10,10000,10,8000,5,4500,5,4500,4,4800,NaN,NaN
1,NaN,NaN,13,25,23300,8,8000,7,5600,3,2700,4,3600,2,2400,1,1000
2,NaN,NaN,20,36,33600,7,7000,8,6400,6,5400,6,5400,2,2400,7,7000
3,NaN,NaN,17,27,24600,6,6000,9,7200,4,3600,4,3600,1,1200,3,3000
4,2,5,29,61,56500,15,15000,18,14400,9,8100,8,7200,4,4800,7,7000

In [ ]:
# obj_cols = df.select_dtypes(include='object').columns
# df[obj_cols] = df[obj_cols].apply(lambda col: col.str.replace(',', '') if col.dtypes == 'object' else col)
df[obj_cols] = df[obj_cols].apply(pd.to_numeric, errors='coerce')
#df[obj_cols] = df[obj_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
# データ型の確認 float
df.dtypes

日付             object
予約件数          float64
予約人数          float64
来客数           float64
総杯数           float64
売上合計(円)       float64
ペールエール(本)     float64
ペールエール(円)     float64
ラガー(本)        float64
ラガー(円)        float64
IPA(本)        float64
IPA(円)        float64
ホワイトビール(本)    float64
ホワイトビール(円)    float64
黒ビール(本)       float64
黒ビール(円)       float64
フルーツビール(本)    float64
フルーツビール(円)    float64
dtype: object

In [ ]:
df.head()

,日付,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
0,2024/04/01,NaN,NaN,21.0,33.0,31800.0,10.0,10000.0,10.0,8000.0,5.0,4500.0,5.0,4500.0,4.0,4800.0,NaN,NaN
1,2024/04/02,NaN,NaN,13.0,25.0,23300.0,8.0,8000.0,7.0,5600.0,3.0,2700.0,4.0,3600.0,2.0,2400.0,1.0,1000.0
2,2024/04/03,NaN,NaN,20.0,36.0,33600.0,7.0,7000.0,8.0,6400.0,6.0,5400.0,6.0,5400.0,2.0,2400.0,7.0,7000.0
3,2024/04/04,NaN,NaN,17.0,27.0,24600.0,6.0,6000.0,9.0,7200.0,4.0,3600.0,4.0,3600.0,1.0,1200.0,3.0,3000.0
4,2024/04/05,2.0,5.0,29.0,61.0,56500.0,15.0,15000.0,18.0,14400.0,9.0,8100.0,8.0,7200.0,4.0,4800.0,7.0,7000.0

In [ ]:
# 各種統計量の確認
df.describe()

,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
count,19.000000,19.000000,314.000000,314.000000,313.000000,310.000000,310.000000,307.000000,307.000000,286.000000,285.000000,257.000000,257.000000,233.000000,233.000000,194.000000,194.000000
mean,1.526316,4.421053,11.818471,21.305732,20160.383387,6.319355,6319.354839,6.283388,4794.462541,3.545455,3202.105263,3.167315,2850.583658,2.776824,3332.188841,2.427835,2427.835052
std,0.611775,2.142579,9.102303,16.192793,15423.303709,4.924473,4924.472889,6.981382,3578.147450,2.424226,2177.395667,2.040417,1836.375520,1.989623,2387.547241,2.058081,2058.081116
min,1.000000,2.000000,1.000000,1.000000,100.000000,1.000000,1000.000000,1.000000,800.000000,0.000000,900.000000,1.000000,900.000000,1.000000,1200.000000,0.000000,0.000000
25%,1.000000,2.000000,3.000000,5.000000,4600.000000,2.000000,2000.000000,2.000000,1600.000000,2.000000,1800.000000,2.000000,1800.000000,1.000000,1200.000000,1.000000,1000.000000
50%,1.000000,4.000000,12.000000,20.000000,19000.000000,6.000000,6000.000000,5.000000,4000.000000,3.000000,2700.000000,3.000000,2700.000000,2.000000,2400.000000,2.000000,2000.000000
75%,2.000000,6.000000,17.000000,30.000000,28400.000000,9.000000,9000.000000,8.000000,6400.000000,5.000000,4500.000000,4.000000,3600.000000,3.000000,3600.000000,3.000000,3000.000000
max,3.000000,8.000000,100.000000,80.000000,79300.000000,25.000000,25000.000000,100.000000,21600.000000,15.000000,13500.000000,12.000000,10800.000000,13.000000,15600.000000,14.000000,14000.000000

In [ ]:
df.isnull().sum()

日付              0
予約件数          296
予約人数          296
来客数             1
総杯数             1
売上合計(円)         2
ペールエール(本)       5
ペールエール(円)       5
ラガー(本)          8
ラガー(円)          8
IPA(本)         29
IPA(円)         30
ホワイトビール(本)     58
ホワイトビール(円)     58
黒ビール(本)        82
黒ビール(円)        82
フルーツビール(本)    121
フルーツビール(円)    121
dtype: int64

In [ ]:
missing_profit = df[df[["売上合計(円)"]].isnull().any(axis=1)]
missing_profit

,日付,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
22,2024/04/26,NaN,NaN,6.0,11.0,NaN,2.0,2000.0,3.0,2400.0,2.0,1800.0,1.0,900.0,2.0,2400.0,1.0,1000.0
191,2024/11/1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.drop(index=191,inplace=True)

In [ ]:
df.at[22, "売上合計(円)"] = df.loc[22, ["ペールエール(円)", "ラガー(円)", "IPA(円)", "ホワイトビール(円)", "黒ビール(円)", "フルーツビール(円)"]].sum()

In [ ]:
#ビールの本数の合計を総杯数に代入
beer_columns = ['ペールエール(本)', 'ラガー(本)', 'IPA(本)', 'ホワイトビール(本)', '黒ビール(本)', 'フルーツビール(本)']
df['ビール本数合計'] = df[beer_columns].sum(axis=1)
df['総杯数'] = df['ビール本数合計']

df.isnull().sum()

日付              0
予約件数          295
予約人数          295
来客数             0
総杯数             0
売上合計(円)         0
ペールエール(本)       4
ペールエール(円)       4
ラガー(本)          7
ラガー(円)          7
IPA(本)         28
IPA(円)         29
ホワイトビール(本)     57
ホワイトビール(円)     57
黒ビール(本)        81
黒ビール(円)        81
フルーツビール(本)    120
フルーツビール(円)    120
ビール本数合計         0
dtype: int64

x1:気温 x2：気圧 y:売上
Y=ax1+bx2+c :係数
y(明日)=a26+b10+c

In [ ]:
df.head()

,日付,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
0,2024/04/01,NaN,NaN,21.0,34.0,31800.0,10.0,10000.0,10.0,8000.0,5.0,4500.0,5.0,4500.0,4.0,4800.0,NaN,NaN
1,2024/04/02,NaN,NaN,13.0,25.0,23300.0,8.0,8000.0,7.0,5600.0,3.0,2700.0,4.0,3600.0,2.0,2400.0,1.0,1000.0
2,2024/04/03,NaN,NaN,20.0,36.0,33600.0,7.0,7000.0,8.0,6400.0,6.0,5400.0,6.0,5400.0,2.0,2400.0,7.0,7000.0
3,2024/04/04,NaN,NaN,17.0,27.0,24600.0,6.0,6000.0,9.0,7200.0,4.0,3600.0,4.0,3600.0,1.0,1200.0,3.0,3000.0
4,2024/04/05,2.0,5.0,29.0,61.0,56500.0,15.0,15000.0,18.0,14400.0,9.0,8100.0,8.0,7200.0,4.0,4800.0,7.0,7000.0

In [ ]:
nan_rows = df[df[beer_columns].isnull().any(axis=1)]

nan_rows

,日付,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
0,2024/04/01,NaN,NaN,21.0,34.0,31800.0,10.0,10000.0,10.0,8000.0,5.0,4500.0,5.0,4500.0,4.0,4800.0,NaN,NaN
5,2024/04/06,NaN,NaN,2.0,4.0,3700.0,1.0,1000.0,1.0,800.0,1.0,900.0,NaN,NaN,NaN,NaN,1.0,1000.0
10,2024/04/12,1.0,2.0,18.0,38.0,34300.0,11.0,11000.0,13.0,10400.0,7.0,6300.0,6.0,5400.0,1.0,1200.0,NaN,NaN
11,2024/04/13,NaN,NaN,2.0,2.0,1800.0,1.0,1000.0,1.0,800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024/04/15,NaN,NaN,3.0,8.0,7500.0,2.0,2000.0,1.0,800.0,2.0,1800.0,1.0,900.0,NaN,NaN,2.0,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,2025/03/18,NaN,NaN,1.0,2.0,2000.0,1.0,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1000.0
316,2025/03/20,NaN,NaN,4.0,5.0,4600.0,2.0,2000.0,1.0,800.0,1.0,900.0,1.0,900.0,NaN,NaN,NaN,NaN
319,2025/03/24,NaN,NaN,20.0,36.0,33900.0,12.0,12000.0,9.0,7200.0,7.0,6300.0,4.0,3600.0,4.0,4800.0,NaN,NaN
322,2025/03/27,NaN,NaN,2.0,4.0,3700.0,1.0,1000.0,1.0,800.0,1.0,900.0,NaN,NaN,NaN,NaN,1.0,1000.0
324,2025/03/29,NaN,NaN,1.0,2.0,1800.0,1.0,1000.0,1.0,800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.loc[nan_rows.index, beer_columns] = df.loc[nan_rows.index, beer_columns].fillna(0)

In [ ]:
df.head()

,日付,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
0,2024/04/01,NaN,NaN,21.0,34.0,31800.0,10.0,10000.0,10.0,8000.0,5.0,4500.0,5.0,4500.0,4.0,4800.0,0.0,NaN
1,2024/04/02,NaN,NaN,13.0,25.0,23300.0,8.0,8000.0,7.0,5600.0,3.0,2700.0,4.0,3600.0,2.0,2400.0,1.0,1000.0
2,2024/04/03,NaN,NaN,20.0,36.0,33600.0,7.0,7000.0,8.0,6400.0,6.0,5400.0,6.0,5400.0,2.0,2400.0,7.0,7000.0
3,2024/04/04,NaN,NaN,17.0,27.0,24600.0,6.0,6000.0,9.0,7200.0,4.0,3600.0,4.0,3600.0,1.0,1200.0,3.0,3000.0
4,2024/04/05,2.0,5.0,29.0,61.0,56500.0,15.0,15000.0,18.0,14400.0,9.0,8100.0,8.0,7200.0,4.0,4800.0,7.0,7000.0

In [ ]:
df.isnull().sum()

日付              0
予約件数          295
予約人数          295
来客数             0
総杯数             0
売上合計(円)         0
ペールエール(本)       0
ペールエール(円)       4
ラガー(本)          0
ラガー(円)          7
IPA(本)          0
IPA(円)         29
ホワイトビール(本)      0
ホワイトビール(円)     57
黒ビール(本)         0
黒ビール(円)        81
フルーツビール(本)      0
フルーツビール(円)    120
dtype: int64

In [ ]:

profit_columns = ['ペールエール(円)', 'ラガー(円)', 'IPA(円)', 'ホワイトビール(円)', '黒ビール(円)', 'フルーツビール(円)']
nan_rows2 = df[df[profit_columns].isnull().any(axis=1)]

In [ ]:
nan_rows2

,日付,予約件数,予約人数,来客数,総杯数,売上合計(円),ペールエール(本),ペールエール(円),ラガー(本),ラガー(円),IPA(本),IPA(円),ホワイトビール(本),ホワイトビール(円),黒ビール(本),黒ビール(円),フルーツビール(本),フルーツビール(円)
0,2024/04/01,NaN,NaN,21.0,34.0,31800.0,10.0,10000.0,10.0,8000.0,5.0,4500.0,5.0,4500.0,4.0,4800.0,0.0,NaN
5,2024/04/06,NaN,NaN,2.0,4.0,3700.0,1.0,1000.0,1.0,800.0,1.0,900.0,0.0,NaN,0.0,NaN,1.0,1000.0
10,2024/04/12,1.0,2.0,18.0,38.0,34300.0,11.0,11000.0,13.0,10400.0,7.0,6300.0,6.0,5400.0,1.0,1200.0,0.0,NaN
11,2024/04/13,NaN,NaN,2.0,2.0,1800.0,1.0,1000.0,1.0,800.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
12,2024/04/15,NaN,NaN,3.0,8.0,7500.0,2.0,2000.0,1.0,800.0,2.0,1800.0,1.0,900.0,0.0,NaN,2.0,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,2025/03/18,NaN,NaN,1.0,2.0,2000.0,1.0,1000.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,1.0,1000.0
316,2025/03/20,NaN,NaN,4.0,5.0,4600.0,2.0,2000.0,1.0,800.0,1.0,900.0,1.0,900.0,0.0,NaN,0.0,NaN
319,2025/03/24,NaN,NaN,20.0,36.0,33900.0,12.0,12000.0,9.0,7200.0,7.0,6300.0,4.0,3600.0,4.0,4800.0,0.0,NaN
322,2025/03/27,NaN,NaN,2.0,4.0,3700.0,1.0,1000.0,1.0,800.0,1.0,900.0,0.0,NaN,0.0,NaN,1.0,1000.0
324,2025/03/29,NaN,NaN,1.0,2.0,1800.0,1.0,1000.0,1.0,800.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN

In [ ]:
df.loc[nan_rows2.index, profit_columns] = df.loc[nan_rows.index, profit_columns].fillna(0)

In [ ]:
df.isnull().sum()

日付              0
予約件数          295
予約人数          295
来客数             0
総杯数             0
売上合計(円)         0
ペールエール(本)       0
ペールエール(円)       0
ラガー(本)          0
ラガー(円)          0
IPA(本)          0
IPA(円)          0
ホワイトビール(本)      0
ホワイトビール(円)      0
黒ビール(本)         0
黒ビール(円)         0
フルーツビール(本)      0
フルーツビール(円)      0
dtype: int64